main: com.chaoticcade.lastpos.Main
name: LastPos
version: 1.0
author: Chaotic Cade
description: Gets last postion of offline player.
commands:
  lastpos:
    description: Returns last position of an offline player
    usage: /lastpos <player>
    permission: lastPos.lastpos
    permission-message: You don't have permission to run this command.
